# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  AZURE_TENANT_ID: '6a425d0d-58f2-4e36-8689-10002b2ec567'
  AZURE_SUBSCRIPTION_ID: '6f4c2473-f8cb-4b18-8796-f4cf662c01fe'
  logicAppsRoot: "$(root)"

pool:
  vmImage: windows-latest

steps:
  - checkout: self
    #- task: AzureKeyVault@1
    #  displayName: Getting credentials for the integration tests
    #  inputs:
    #    azureSubscription: ${{variables.subscription}}
    #    KeyVaultName: ${{variables.keyVault}}
    #    SecretsFilter: 'adoClientId,adoClientSecret'
    #    RunAsPreJob: false
  - bash: |
            echo "##vso[task.setvariable variable=AZURE_CLIENT_ID]$('0eD2iTTYL2T-p__~1xO_XR0N.46k6XyfcI')"
            echo "##vso[task.setvariable variable=AZURE_CLIENT_SECRET]$('6821c416-d52e-4b27-8ce4-9202fc3a24c4')"
  - script: |
        echo $(root)
        echo ${{logicAppsRoot}}
    displayName: 'Run a multi-line script'
  - task: AzureResourceGroupDeployment@2
    displayName: BuyTicketCorinthians ARM Deploy
    inputs:
      azureSubscription: serviceConnectionDevOps
      action: "Create Or Update Resource Group"
      resourceGroupName: ACSUG-LogicApps-Testing
      templateLocation: "Linked artifact"
      csmFile: ${{variables.logicAppsRoot}}/logicapptesting/BuyTicketCorinthians/BuyTicketCorinthians.json
      csmParametersFile: ${{variables.logicAppsRoot}}/logicapptesting/BuyTicketCorinthians/dev.parameters.json
      deploymentMode: "Incremental"
      deploymentName: BuyTicketCorinthians