# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  ACSUG_TENANT_ID: '7c2add57-ad63-4a62-bea3-fc5440ea5e63'
  ACSUG_SUBSCRIPTION_ID: '9a351677-dd5f-4242-ac24-ca47976bf412'

pool:
  vmImage: windows-latest

steps:
  - checkout: self
    #- task: AzureKeyVault@1
    #  displayName: Getting credentials for the integration tests
    #  inputs:
    #    azureSubscription: ${{variables.subscription}}
    #    KeyVaultName: ${{variables.keyVault}}
    #    SecretsFilter: 'adoClientId,adoClientSecret'
    #    RunAsPreJob: false
  - bash: |
            echo "##vso[task.setvariable variable=ACSUG_CLIENT_ID]$('281c97cf-9f68-4c25-8e10-66c3776935e1')"
            echo "##vso[task.setvariable variable=ACSUG_CLIENT_SECRET]$('A4200cS4nQEm8mq.X~4FQPxZ-4If9_Q-N~')"
  - task: AzureResourceGroupDeployment@2
    displayName: BuyTicketCorinthians ARM Deploy
    inputs:
      azureSubscription: serviceConnectionDevOps
      action: "Create Or Update Resource Group"
      resourceGroupName: ACSUG-LogicApps-Testing
      templateLocation: "Linked artifact"
      csmFile: BuyTicketCorinthians/BuyTicketCorinthians.json
      csmParametersFile: BuyTicketCorinthians/dev.parameters.json
      deploymentMode: "Incremental"
      deploymentName: BuyTicketCorinthians
  - task: NuGetCommand@2
    displayName: Restore packages
    inputs:
      command: restore
      restoreSolution: BuyTicketCorinthians.Tests/BuyTicketCorinthians.Tests.csproj
      feedsToUse: select
      restoreDirectory: '$(Build.SourcesDirectory)\lapp-buyticketcorinthians-dev.IntegrationTests\packages'
  - task: VSBuild@1
    displayName: Build Test
    inputs:
      solution: BuyTicketCorinthians.Tests/BuyTicketCorinthians.Tests.csproj
      msBuildArgs: '/p:OutputPath=$(System.DefaultWorkingDirectory)'
      platform: 'Any CPU'
      configuration: 'Debug'
  - task: VSTest@2
    displayName: Execute Tests
    inputs:
      testAssemblyVer2: |
        **\BuyTicketCorinthians.Tests.dll
        !**\*TestAdapter.dll
        !**\obj\**
      searchFolder: '$(System.DefaultWorkingDirectory)'
      platform: 'Any CPU'
      configuration: 'Debug'